/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loredoclicker;

import javax.swing.*;
import java.awt.BorderLayout;
import java.io.File;
import javax.swing.ImageIcon;
import java.util.TimerTask;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;

/**
 *
 * @author LucasRezende
 */
public class mainscreen extends javax.swing.JPanel {

	Clip audioClip;
    JFrame newFrame = new JFrame(); //Cria um JFrame
    int cabelos = 0; //Cria o contador de cabelos
    int upPeruca = 1, precoPeruca = 20; //Cria o contador da peruca
    int upTonico = 1, precoTonico = 10; //Cria o contador do tonico
	int upShampoo = 60, precoShampoo = 400;

    java.util.Timer timer = new java.util.Timer(); //Cria o timer dos clicks

    /**
     * Creates new form mainscreen
     */
    public mainscreen() { //Configuração da mainscreen
        initComponents();
        newFrame.getContentPane().add(this, BorderLayout.CENTER);
        newFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        newFrame.pack();

        newFrame.setTitle("LoredoClicker");
        labelCabelos.setText(cabelos + "");
        labelTonico.setText(precoTonico + "");
        labelPeruca.setText(precoPeruca + "");
		labelShampoo.setText(precoShampoo + "");

        ImageIcon loredo = new ImageIcon("assets/loredo_clicker.png");
        ImageIcon peruca = new ImageIcon("assets/peruca.png");
        ImageIcon tonico = new ImageIcon("assets/tonico.png");
		ImageIcon shampoo = new ImageIcon("assets/shampoo.png");
        buttonLoredo.setIcon(loredo);
        buttonPeruca.setIcon(peruca);
        buttonTonico.setIcon(tonico);
		buttonShampoo.setIcon(shampoo);

		newFrame.setSize(800, 600);
		newFrame.setResizable(false);
		newFrame.setLocationRelativeTo(null);
		newFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonLoredo = new javax.swing.JButton();
        labelCabelos = new javax.swing.JLabel();
        buttonPeruca = new javax.swing.JButton();
        buttonTonico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelTonico = new javax.swing.JLabel();
        labelPeruca = new javax.swing.JLabel();
        buttonShampoo = new javax.swing.JButton();
        labelShampoo = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        buttonLoredo.setBackground(new java.awt.Color(51, 204, 255));
        buttonLoredo.setContentAreaFilled(false);
        buttonLoredo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonLoredoActionPerformed(evt);
            }
        });

        labelCabelos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCabelos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCabelos.setText("Cabelos");

        buttonPeruca.setBackground(new java.awt.Color(255, 255, 255));
        buttonPeruca.setText("Peruca");
        buttonPeruca.setToolTipText("");
        buttonPeruca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPerucaActionPerformed(evt);
            }
        });

        buttonTonico.setBackground(new java.awt.Color(255, 255, 255));
        buttonTonico.setText("Tônico");
        buttonTonico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonTonicoActionPerformed(evt);
            }
        });

        labelTonico.setText("PrecoTonico");

        labelPeruca.setText("PrecoPeruca");

        buttonShampoo.setBackground(new java.awt.Color(255, 255, 255));
        buttonShampoo.setText("Shampoo");
        buttonShampoo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonShampooActionPerformed(evt);
            }
        });

        labelShampoo.setText("PrecoShampoo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLoredo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTonico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonTonico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPeruca)
                            .addComponent(labelShampoo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonShampoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPeruca, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(labelCabelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelCabelos, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTonico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(labelTonico))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPeruca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPeruca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonShampoo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelShampoo)))
                    .addComponent(buttonLoredo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoredoActionPerformed
    }//GEN-LAST:event_buttonLoredoActionPerformed

    private void buttonPerucaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerucaActionPerformed
    }//GEN-LAST:event_buttonPerucaActionPerformed

    private void buttonTonicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTonicoActionPerformed
    }//GEN-LAST:event_buttonTonicoActionPerformed

    private void buttonShampooActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonShampooActionPerformed
    {//GEN-HEADEREND:event_buttonShampooActionPerformed
    }//GEN-LAST:event_buttonShampooActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoredo;
    private javax.swing.JButton buttonPeruca;
    private javax.swing.JButton buttonShampoo;
    private javax.swing.JButton buttonTonico;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCabelos;
    private javax.swing.JLabel labelPeruca;
    private javax.swing.JLabel labelShampoo;
    private javax.swing.JLabel labelTonico;
    // End of variables declaration//GEN-END:variables
}
